### ISSUE TITLE
Install location

### ISSUE THREAD

**Issue by ghost** [ThePBone/Viper4Linux-GUI#1] opened 2019-06-16 17:33 UTC
Might want to drop the binary in /usr/local/bin for sanity reasons. Just a thought. 

https://unix.stackexchange.com/questions/8656/usr-bin-vs-usr-local-bin-on-linux  

And the spec: http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html

**Comment by ThePBone** [comment] 2019-06-24 16:05
Good idea! At the moment I don't have much time, but I will update the installation path as soon as I can. However I might need to include some kind of script to make sure that there is no duplicate of the binary at /usr/bin for people who update from the older version

**Comment by L3vi47h4N** [comment] 2019-06-27 21:58
Ah for sure. The other thing to consider too is that installs that the package manager is responsible for _should_ still go in /usr/bin so those aur arch people and any future deb packages should continue to drop it there.

Another thing we might want to consider doing is splitting out the driver install from my process and packaging viper4linux and your gui into a flatpak/appimage as a release option. ¯\_(ツ)_/¯

**Comment by ThePBone** [comment] 2019-06-27 22:35
Ah okay, I think I misunderstood you there. If we leave the aur-package as it is, I do not have to change much, except the install script for Debian I provide at the moment.
I quickly pushed an update for it

**Closed** 2019-08-05 13:06 UTC
